### ISSUE TITLE
Ability to run more than one environment at a time

### ISSUE THREAD

**Issue by PaulDuvall** [stelligent/nando_automation_demo#10]
This could be in different regions on an AWS account.
Priority: Medium

**Comment by nand0p** [comment]
the only thing that blocks multiple versions of demo are CNAMES as they are global.   this can be fixed by adding region to CNAME.  ie.   "stelligent-automation-demo-us-east-1.elasticoperations.com"

**Comment by nand0p** [comment]
we may want to add that an environment (instance of the demo) can run in multiple regions. (demo region failover/balancing)

**Comment by PaulDuvall** [comment]
I actually don't currently understand why we cannot run as many environments as we want in the same region or in multiple regions. Seems like we'd just use different subdomains for each. Would like to discuss.

**Comment by NickDeClario** [comment]
I actually spoke to Nando about this and I would like to work towards this.  I don't think it's that much of an effort above what was done for multi-region support at this point.

**Comment by NickDeClario** [comment]
Multiple instants across multiple regions is now supported.  The regions are currently limited to us-west-2 and us-east-1.  I'll look in to adding the necessary configuration information for other regions that currently support codedeploy.
