### ISSUE TITLE
break out cloudformation template into individual templates

### ISSUE THREAD

**Issue by nand0p** [stelligent/nando_automation_demo#2]
create jenkins jobs via seed dsl to kill/relaunch individual templates.

```
vpc
rds
jenkins
codedeploy asg
docker eb (ecs)
```

**Comment by nand0p** [comment]
will peer with @trikosuave on this one if hes available this week

**Comment by trikosuave** [comment]
vpc/sg/rds/eb are done.
still needed, s3/jenkins.

**Comment by trikosuave** [comment]
s3/ecs/eb are out, need to do jenkins/asg.
