### ISSUE TITLE
secrets management

### ISSUE THREAD

**Issue by nand0p** [stelligent/nando_automation_demo#22]
Currently secrets are in plain text.   they are either protected by S3 policy or AWS GUI or CLI access (aws cfn describe-stacks: "PrivateKey" parameter).  We should integrate KMS into the demo, and possibly a secondary tool for storing secrets on the instances themselves where necessary, such as in-memory fuse fs https://github.com/square/keywhiz.  

We should probably also look at Vault https://hashicorp.com/blog/vault.html.

**Comment by trikosuave** [comment]
Going to add jenkins password to python script.
Will attempt to store instagram keys in KMS.

**Comment by trikosuave** [comment]
Removed Instagram. Jenkins credentials are set in python script and can be set via ./go.py options, including a password prompt.
