### ISSUE TITLE
demo instance temp s3 bucket

### ISSUE THREAD

**Issue by nand0p** [stelligent/nando_automation_demo#23]
the temporary cfn created s3 bucket should have index.html as public at bucket root, which describes the demo instance version

all directories in the temp bucket should be private (s3 policy via trusted ips) and store all logs for all aws resources. (ELBs, RDP, etc)

for instance application logs (ie. nginx, syslog, etc), we could explore streaming to Kinesis, processing with Lambda, and then writing out to this tmp S3 bucket

**Comment by NickDeClario** [comment]
The first part of this is completed, an index.html file is now being placed.  This was done in regards to getting all the cfn outputs sorted.
