### ISSUE TITLE
rename demo and remove all hardcoded values

### ISSUE THREAD

**Issue by nand0p** [stelligent/nando_automation_demo#7]
remove all hardcoded values and rename demo to "stelligent_automation_demo"
- s/nando/stelligent/g

**Comment by PaulDuvall** [comment]
Priority for demo: Low

**Comment by nand0p** [comment]
stelligent-automation-demo could always cname to the latest running demo instance....  so delete cname fist if exists, and then add it back. can cfn test for cname existance? this might have to be part of go.py..... so url is always same with latest code http://steligent-automation-demo.elasticopterations.com, no matter what region, or multiregion loadbalancing/repilcation/disribution

**Comment by trikosuave** [comment]
separating out the templates helped a lot with this. I will be working on removing the rest in the next week.

**Comment by trikosuave** [comment]
Moved to stelligent_demo, removed all nando names. hardcoded items are still there but will need to be broken into smaller tasks.
